steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-to-cloud-run"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy ${_SERVICE} \
          --image ${_NEXTJS_IMAGE} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets DATABASE_URL=${_DATABASE_URL_SECRET_NAME}:latest \
          --set-secrets NEXTAUTH_SECRET=${_NEXTAUTH_SECRET_SECRET_NAME}:latest \
          --set-env-vars NODE_ENV=${_NODE_ENV} \
          --set-env-vars NEXTAUTH_URL=${_NEXTAUTH_URL} \
          --set-env-vars NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL} \
          --cpu 1 \
          --memory 2Gi \
          --max-instances 10 \
          --min-instances 0

substitutions:
  _TAG_NAME: "tag-name"
  _ENV: "dev"
  _SERVICE: "nextjs-dev"
  _NODE_ENV: "development"
  _NEXTJS_IMAGE: "us-central1-docker.pkg.dev/${PROJECT_ID}/containers/nextjs-${_ENV}:${_TAG_NAME}"
  _NEXTAUTH_URL: ""
  _NEXT_PUBLIC_APP_URL: ""
  _DATABASE_URL_SECRET_NAME: "DATABASE_URL_DEV"
  _NEXTAUTH_SECRET_SECRET_NAME: "NEXTAUTH_SECRET_DEV"

options:
  dynamic_substitutions: true
